platform :ios, '9.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'


target 'Js2NativeDemo' do
    pod 'MessengerDog', :path => '/Users/lion/sourcetree-workspace/librarys/MessengerDog'
end
